using System.IO;
using System.Text;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Win32;

namespace GrblPlotter.Wpf.ViewModels;

/// <summary>Loads a raster image, thresholds it, and generates raster laser-engraving G-code
/// (alternating scan direction, laser on/off runs) using only built-in WPF imaging (no extra NuGet).</summary>
public partial class ImageCreateViewModel : ObservableObject
{
    public event Action<string>? GCodeGenerated;

    [ObservableProperty] private string? _imagePath;
    [ObservableProperty] private BitmapImage? _preview;
    [ObservableProperty] private double _targetWidthMm = 100;
    [ObservableProperty] private int _threshold = 128;
    [ObservableProperty] private double _lineIntervalMm = 0.5;
    [ObservableProperty] private int _laserPower = 800;
    [ObservableProperty] private double _feedRate = 1500;
    [ObservableProperty] private bool _invert;
    [ObservableProperty] private string _statusText = "";
    [ObservableProperty] private string _previewGCode = "";

    private byte[]? _gray;
    private int _pixelWidth;
    private int _pixelHeight;

    [RelayCommand]
    private void PickImage()
    {
        var dlg = new OpenFileDialog { Filter = "Images (*.png;*.jpg;*.jpeg;*.bmp)|*.png;*.jpg;*.jpeg;*.bmp" };
        if (dlg.ShowDialog() != true) return;
        LoadImage(dlg.FileName);
    }

    private void LoadImage(string path)
    {
        var src = new BitmapImage();
        src.BeginInit();
        src.CacheOption = BitmapCacheOption.OnLoad;
        src.UriSource = new Uri(path);
        src.EndInit();
        Preview = src;
        ImagePath = path;

        var gray = new FormatConvertedBitmap(src, PixelFormats.Gray8, null, 0);
        _pixelWidth = gray.PixelWidth;
        _pixelHeight = gray.PixelHeight;
        _gray = new byte[_pixelWidth * _pixelHeight];
        gray.CopyPixels(_gray, _pixelWidth, 0);
        StatusText = $"loaded {Path.GetFileName(path)} ({_pixelWidth}x{_pixelHeight}px)";
    }

    [RelayCommand]
    private void Generate()
    {
        if (_gray == null)
        {
            StatusText = "pick an image first";
            return;
        }
        var gcode = BuildRasterGCode();
        PreviewGCode = gcode.Length > 4000 ? gcode[..4000] + "\n; …truncated preview…" : gcode;
        GCodeGenerated?.Invoke(gcode);
        StatusText = "engraving g-code generated";
    }

    private string BuildRasterGCode()
    {
        var mmPerPxX = TargetWidthMm / _pixelWidth;
        var targetHeightMm = _pixelHeight * mmPerPxX;
        var rowStepPx = Math.Max(1, (int)Math.Round(LineIntervalMm / mmPerPxX));

        var sb = new StringBuilder();
        sb.AppendLine("; raster engraving generated by GRBL-Plotter WPF ImageCreate");
        sb.AppendLine(FormattableString.Invariant($"; source {_pixelWidth}x{_pixelHeight}px -> {TargetWidthMm:0.#}x{targetHeightMm:0.#}mm"));
        sb.AppendLine("G90 G21");
        sb.AppendLine("M5");

        var leftToRight = true;
        for (var py = 0; py < _pixelHeight; py += rowStepPx)
        {
            var y = targetHeightMm - py * mmPerPxX;
            var laserOn = false;

            var columns = leftToRight ? Enumerable.Range(0, _pixelWidth) : Enumerable.Range(0, _pixelWidth).Reverse();
            foreach (var px in columns)
            {
                var v = _gray![py * _pixelWidth + px];
                var dark = Invert ? v > Threshold : v < Threshold;
                var x = px * mmPerPxX;

                if (dark && !laserOn)
                {
                    sb.AppendLine(FormattableString.Invariant($"G0 X{x:0.###} Y{y:0.###}"));
                    sb.AppendLine(FormattableString.Invariant($"M3 S{LaserPower}"));
                    laserOn = true;
                }
                else if (!dark && laserOn)
                {
                    sb.AppendLine(FormattableString.Invariant($"G1 X{x:0.###} Y{y:0.###} F{FeedRate:0.###}"));
                    sb.AppendLine("M5");
                    laserOn = false;
                }
            }

            if (laserOn)
            {
                var lastX = (leftToRight ? _pixelWidth - 1 : 0) * mmPerPxX;
                sb.AppendLine(FormattableString.Invariant($"G1 X{lastX:0.###} Y{y:0.###} F{FeedRate:0.###}"));
                sb.AppendLine("M5");
            }
            leftToRight = !leftToRight;
        }

        sb.AppendLine("M5");
        return sb.ToString();
    }
}
