using System.Text;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace GrblPlotter.Wpf.ViewModels;

public enum ShapeType
{
    Rectangle,
    Circle,
    Polygon,
    Star,
    Line
}

/// <summary>Parametric shape generator (rectangle / circle / regular polygon / star / line) -> pen/laser G-code.</summary>
public partial class ShapeCreateViewModel : ObservableObject
{
    public event Action<string>? GCodeGenerated;

    public Array ShapeTypes { get; } = Enum.GetValues(typeof(ShapeType));

    [ObservableProperty] private ShapeType _shapeType = ShapeType.Rectangle;
    [ObservableProperty] private double _width = 50;
    [ObservableProperty] private double _height = 30;
    [ObservableProperty] private double _diameter = 40;
    [ObservableProperty] private int _sides = 6;
    [ObservableProperty] private double _originX;
    [ObservableProperty] private double _originY;
    [ObservableProperty] private double _penDownZ = -1;
    [ObservableProperty] private double _penUpZ = 2;
    [ObservableProperty] private double _feedRate = 1000;
    [ObservableProperty] private string _previewGCode = "";
    [ObservableProperty] private string _statusText = "";

    [RelayCommand]
    private void Generate()
    {
        var points = BuildPoints();
        var gcode = ToGCode(points);
        PreviewGCode = gcode;
        GCodeGenerated?.Invoke(gcode);
        StatusText = $"generated {ShapeType} with {points.Count} points";
    }

    private List<(double X, double Y)> BuildPoints()
    {
        var pts = new List<(double X, double Y)>();
        switch (ShapeType)
        {
            case ShapeType.Rectangle:
                pts.Add((OriginX, OriginY));
                pts.Add((OriginX + Width, OriginY));
                pts.Add((OriginX + Width, OriginY + Height));
                pts.Add((OriginX, OriginY + Height));
                pts.Add((OriginX, OriginY));
                break;

            case ShapeType.Line:
                pts.Add((OriginX, OriginY));
                pts.Add((OriginX + Width, OriginY + Height));
                break;

            case ShapeType.Circle:
            {
                var r = Diameter / 2;
                var cx = OriginX + r;
                var cy = OriginY + r;
                for (var i = 0; i <= 64; i++)
                {
                    var a = 2 * Math.PI * i / 64;
                    pts.Add((cx + r * Math.Cos(a), cy + r * Math.Sin(a)));
                }
                break;
            }

            case ShapeType.Polygon:
            {
                var n = Math.Max(3, Sides);
                var r = Diameter / 2;
                var cx = OriginX + r;
                var cy = OriginY + r;
                for (var i = 0; i <= n; i++)
                {
                    var a = 2 * Math.PI * i / n - Math.PI / 2;
                    pts.Add((cx + r * Math.Cos(a), cy + r * Math.Sin(a)));
                }
                break;
            }

            case ShapeType.Star:
            {
                var n = Math.Max(3, Sides);
                var rOuter = Diameter / 2;
                var rInner = rOuter * 0.45;
                var cx = OriginX + rOuter;
                var cy = OriginY + rOuter;
                for (var i = 0; i <= n * 2; i++)
                {
                    var a = Math.PI * i / n - Math.PI / 2;
                    var r = i % 2 == 0 ? rOuter : rInner;
                    pts.Add((cx + r * Math.Cos(a), cy + r * Math.Sin(a)));
                }
                break;
            }
        }
        return pts;
    }

    private string ToGCode(List<(double X, double Y)> pts)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"; {ShapeType} shape generated by GRBL-Plotter WPF ShapeCreate");
        sb.AppendLine("G90 G21");
        sb.AppendLine(FormattableString.Invariant($"G0 Z{PenUpZ:0.###}"));
        if (pts.Count == 0) return sb.ToString();

        sb.AppendLine(FormattableString.Invariant($"G0 X{pts[0].X:0.###} Y{pts[0].Y:0.###}"));
        sb.AppendLine(FormattableString.Invariant($"G1 Z{PenDownZ:0.###} F{FeedRate:0.###}"));
        for (var i = 1; i < pts.Count; i++)
            sb.AppendLine(FormattableString.Invariant($"G1 X{pts[i].X:0.###} Y{pts[i].Y:0.###} F{FeedRate:0.###}"));
        sb.AppendLine(FormattableString.Invariant($"G0 Z{PenUpZ:0.###}"));
        return sb.ToString();
    }
}
