using System.Globalization;
using System.Text;
using System.Windows;
using System.Windows.Media;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace GrblPlotter.Wpf.ViewModels;

/// <summary>Renders text using the installed system font's outline geometry (WPF <see cref="FormattedText"/>)
/// and converts the flattened outline into pen-plotter style G-code (no extra font/vector dependency).</summary>
public partial class TextCreateViewModel : ObservableObject
{
    public event Action<string>? GCodeGenerated;

    [ObservableProperty] private string _text = "Hello";
    [ObservableProperty] private double _fontSize = 20;
    [ObservableProperty] private string _fontFamily = "Arial";
    [ObservableProperty] private double _penDownZ = -1;
    [ObservableProperty] private double _penUpZ = 2;
    [ObservableProperty] private double _feedRate = 1000;
    [ObservableProperty] private string _previewGCode = "";
    [ObservableProperty] private string _statusText = "";

    [RelayCommand]
    private void Generate()
    {
        if (string.IsNullOrEmpty(Text))
        {
            StatusText = "enter some text first";
            return;
        }
        var gcode = BuildGCode();
        PreviewGCode = gcode;
        GCodeGenerated?.Invoke(gcode);
        StatusText = $"generated {gcode.Split('\n').Length} lines for \"{Text}\"";
    }

    private string BuildGCode()
    {
        var typeface = new Typeface(new FontFamily(FontFamily), FontStyles.Normal, FontWeights.Normal, FontStretches.Normal);
        var formatted = new FormattedText(Text, CultureInfo.InvariantCulture, FlowDirection.LeftToRight,
            typeface, FontSize, Brushes.Black, 1.0);
        var geometry = formatted.BuildGeometry(new Point(0, 0));
        var flattened = geometry.GetFlattenedPathGeometry(0.25, ToleranceType.Absolute);
        var totalHeight = formatted.Height;

        var sb = new StringBuilder();
        sb.AppendLine("; text engraving generated by GRBL-Plotter WPF TextCreate");
        sb.AppendLine("G90 G21");
        sb.AppendLine(FormattableString.Invariant($"G0 Z{PenUpZ:0.###}"));

        foreach (var figure in flattened.Figures)
        {
            var start = ToMachine(figure.StartPoint, totalHeight);
            sb.AppendLine(FormattableString.Invariant($"G0 X{start.X:0.###} Y{start.Y:0.###}"));
            sb.AppendLine(FormattableString.Invariant($"G1 Z{PenDownZ:0.###} F{FeedRate:0.###}"));

            foreach (var seg in figure.Segments)
            {
                switch (seg)
                {
                    case PolyLineSegment poly:
                        foreach (var p in poly.Points)
                        {
                            var mp = ToMachine(p, totalHeight);
                            sb.AppendLine(FormattableString.Invariant($"G1 X{mp.X:0.###} Y{mp.Y:0.###} F{FeedRate:0.###}"));
                        }
                        break;
                    case LineSegment line:
                        var lp = ToMachine(line.Point, totalHeight);
                        sb.AppendLine(FormattableString.Invariant($"G1 X{lp.X:0.###} Y{lp.Y:0.###} F{FeedRate:0.###}"));
                        break;
                }
            }

            if (figure.IsClosed)
            {
                var close = ToMachine(figure.StartPoint, totalHeight);
                sb.AppendLine(FormattableString.Invariant($"G1 X{close.X:0.###} Y{close.Y:0.###} F{FeedRate:0.###}"));
            }
            sb.AppendLine(FormattableString.Invariant($"G0 Z{PenUpZ:0.###}"));
        }

        sb.AppendLine(FormattableString.Invariant($"G0 Z{PenUpZ:0.###}"));
        return sb.ToString();
    }

    private static Point ToMachine(Point p, double totalHeight) => new(p.X, totalHeight - p.Y);
}
