//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRBL_Plotter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string port1 {
            get {
                return ((string)(this["port1"]));
            }
            set {
                this["port1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public string baud1 {
            get {
                return ((string)(this["baud1"]));
            }
            set {
                this["baud1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\")]
        public string file {
            get {
                return ((string)(this["file"]));
            }
            set {
                this["file"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Set new coord|G43.1 Z-31.628 ; G92 X140 Y0 Z32")]
        public string custom1 {
            get {
                return ((string)(this["custom1"]));
            }
            set {
                this["custom1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Move to 0;0;0|G90 G0 X0 Y0 Z0")]
        public string custom2 {
            get {
                return ((string)(this["custom2"]));
            }
            set {
                this["custom2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tray Out|G91 G53 G0 Z-1;G90 G53 G0 Y-5")]
        public string custom3 {
            get {
                return ((string)(this["custom3"]));
            }
            set {
                this["custom3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tray In|G90 G53 G0 Y-160")]
        public string custom4 {
            get {
                return ((string)(this["custom4"]));
            }
            set {
                this["custom4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pen remove|_misc\\script_pen_remove.nc")]
        public string custom5 {
            get {
                return ((string)(this["custom5"]));
            }
            set {
                this["custom5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pen pickup|_misc\\script_pen_pickup.nc")]
        public string custom6 {
            get {
                return ((string)(this["custom6"]));
            }
            set {
                this["custom6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pen probing|_misc\\script_probing_tool.nc")]
        public string custom7 {
            get {
                return ((string)(this["custom7"]));
            }
            set {
                this["custom7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Set Pen 0|G92 Z25")]
        public string custom8 {
            get {
                return ((string)(this["custom8"]));
            }
            set {
                this["custom8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int camerindex {
            get {
                return ((int)(this["camerindex"]));
            }
            set {
                this["camerindex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public float camerarotation {
            get {
                return ((float)(this["camerarotation"]));
            }
            set {
                this["camerarotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double camerascalingTop {
            get {
                return ((double)(this["camerascalingTop"]));
            }
            set {
                this["camerascalingTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double camerascalingBot {
            get {
                return ((double)(this["camerascalingBot"]));
            }
            set {
                this["camerascalingBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double cameraTeachRadiusTop {
            get {
                return ((double)(this["cameraTeachRadiusTop"]));
            }
            set {
                this["cameraTeachRadiusTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double cameraTeachRadiusBot {
            get {
                return ((double)(this["cameraTeachRadiusBot"]));
            }
            set {
                this["cameraTeachRadiusBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cameraPosTop {
            get {
                return ((double)(this["cameraPosTop"]));
            }
            set {
                this["cameraPosTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-50")]
        public double cameraPosBot {
            get {
                return ((double)(this["cameraPosBot"]));
            }
            set {
                this["cameraPosBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cameraToolOffsetX {
            get {
                return ((double)(this["cameraToolOffsetX"]));
            }
            set {
                this["cameraToolOffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cameraToolOffsetY {
            get {
                return ((double)(this["cameraToolOffsetY"]));
            }
            set {
                this["cameraToolOffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double lastOffsetX {
            get {
                return ((double)(this["lastOffsetX"]));
            }
            set {
                this["lastOffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double lastOffsetY {
            get {
                return ((double)(this["lastOffsetY"]));
            }
            set {
                this["lastOffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double lastOffsetZ {
            get {
                return ((double)(this["lastOffsetZ"]));
            }
            set {
                this["lastOffsetZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color colorBackground {
            get {
                return ((global::System.Drawing.Color)(this["colorBackground"]));
            }
            set {
                this["colorBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 192")]
        public global::System.Drawing.Color colorRuler {
            get {
                return ((global::System.Drawing.Color)(this["colorRuler"]));
            }
            set {
                this["colorRuler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color colorPenUp {
            get {
                return ((global::System.Drawing.Color)(this["colorPenUp"]));
            }
            set {
                this["colorPenUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color colorPenDown {
            get {
                return ((global::System.Drawing.Color)(this["colorPenDown"]));
            }
            set {
                this["colorPenDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color colorTool {
            get {
                return ((global::System.Drawing.Color)(this["colorTool"]));
            }
            set {
                this["colorTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal widthRuler {
            get {
                return ((decimal)(this["widthRuler"]));
            }
            set {
                this["widthRuler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public decimal widthPenUp {
            get {
                return ((decimal)(this["widthPenUp"]));
            }
            set {
                this["widthPenUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public decimal widthPenDown {
            get {
                return ((decimal)(this["widthPenDown"]));
            }
            set {
                this["widthPenDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public decimal widthTool {
            get {
                return ((decimal)(this["widthTool"]));
            }
            set {
                this["widthTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeepPink")]
        public global::System.Drawing.Color colorMarker {
            get {
                return ((global::System.Drawing.Color)(this["colorMarker"]));
            }
            set {
                this["colorMarker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal widthMarker {
            get {
                return ((decimal)(this["widthMarker"]));
            }
            set {
                this["widthMarker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int textFontIndex {
            get {
                return ((int)(this["textFontIndex"]));
            }
            set {
                this["textFontIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal textFontSize {
            get {
                return ((decimal)(this["textFontSize"]));
            }
            set {
                this["textFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal importGCZUp {
            get {
                return ((decimal)(this["importGCZUp"]));
            }
            set {
                this["importGCZUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2")]
        public decimal importGCZDown {
            get {
                return ((decimal)(this["importGCZDown"]));
            }
            set {
                this["importGCZDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal importGCZFeed {
            get {
                return ((decimal)(this["importGCZFeed"]));
            }
            set {
                this["importGCZFeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal importGCSSpeed {
            get {
                return ((decimal)(this["importGCSSpeed"]));
            }
            set {
                this["importGCSSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test")]
        public string textFontText {
            get {
                return ((string)(this["textFontText"]));
            }
            set {
                this["textFontText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importGCZEnable {
            get {
                return ((bool)(this["importGCZEnable"]));
            }
            set {
                this["importGCZEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool importGCSpindleToggle {
            get {
                return ((bool)(this["importGCSpindleToggle"]));
            }
            set {
                this["importGCSpindleToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importGCAddComments {
            get {
                return ((bool)(this["importGCAddComments"]));
            }
            set {
                this["importGCAddComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public decimal importGCXYFeed {
            get {
                return ((decimal)(this["importGCXYFeed"]));
            }
            set {
                this["importGCXYFeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G90 G1 M3")]
        public string importGCHeader {
            get {
                return ((string)(this["importGCHeader"]));
            }
            set {
                this["importGCHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M5; G0 X0 Y0; M30")]
        public string importGCFooter {
            get {
                return ((string)(this["importGCFooter"]));
            }
            set {
                this["importGCFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool importGCPWMEnable {
            get {
                return ((bool)(this["importGCPWMEnable"]));
            }
            set {
                this["importGCPWMEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public decimal importGCPWMUp {
            get {
                return ((decimal)(this["importGCPWMUp"]));
            }
            set {
                this["importGCPWMUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public decimal importGCPWMDown {
            get {
                return ((decimal)(this["importGCPWMDown"]));
            }
            set {
                this["importGCPWMDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal importGCPWMDlyUp {
            get {
                return ((decimal)(this["importGCPWMDlyUp"]));
            }
            set {
                this["importGCPWMDlyUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal importGCPWMDlyDown {
            get {
                return ((decimal)(this["importGCPWMDlyDown"]));
            }
            set {
                this["importGCPWMDlyDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal importSVGBezier {
            get {
                return ((decimal)(this["importSVGBezier"]));
            }
            set {
                this["importSVGBezier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importSVGRezise {
            get {
                return ((bool)(this["importSVGRezise"]));
            }
            set {
                this["importSVGRezise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal importSVGMaxSize {
            get {
                return ((decimal)(this["importSVGMaxSize"]));
            }
            set {
                this["importSVGMaxSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool importSVGAddComments {
            get {
                return ((bool)(this["importSVGAddComments"]));
            }
            set {
                this["importSVGAddComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importSVGReduce {
            get {
                return ((bool)(this["importSVGReduce"]));
            }
            set {
                this["importSVGReduce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal importSVGReduceLimit {
            get {
                return ((decimal)(this["importSVGReduceLimit"]));
            }
            set {
                this["importSVGReduceLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool importSVGPauseElement {
            get {
                return ((bool)(this["importSVGPauseElement"]));
            }
            set {
                this["importSVGPauseElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool importSVGPausePenDown {
            get {
                return ((bool)(this["importSVGPausePenDown"]));
            }
            set {
                this["importSVGPausePenDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool importSVGPathExtend {
            get {
                return ((bool)(this["importSVGPathExtend"]));
            }
            set {
                this["importSVGPathExtend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point locationSerForm1 {
            get {
                return ((global::System.Drawing.Point)(this["locationSerForm1"]));
            }
            set {
                this["locationSerForm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point locationMForm {
            get {
                return ((global::System.Drawing.Point)(this["locationMForm"]));
            }
            set {
                this["locationMForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point locationSetForm {
            get {
                return ((global::System.Drawing.Point)(this["locationSetForm"]));
            }
            set {
                this["locationSetForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point locationCamForm {
            get {
                return ((global::System.Drawing.Point)(this["locationCamForm"]));
            }
            set {
                this["locationCamForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool serialMinimize {
            get {
                return ((bool)(this["serialMinimize"]));
            }
            set {
                this["serialMinimize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM2")]
        public string port2 {
            get {
                return ((string)(this["port2"]));
            }
            set {
                this["port2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public string baud2 {
            get {
                return ((string)(this["baud2"]));
            }
            set {
                this["baud2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point locationSerForm2 {
            get {
                return ((global::System.Drawing.Point)(this["locationSerForm2"]));
            }
            set {
                this["locationSerForm2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importSVGToolColor {
            get {
                return ((bool)(this["importSVGToolColor"]));
            }
            set {
                this["importSVGToolColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importGCTool {
            get {
                return ((bool)(this["importGCTool"]));
            }
            set {
                this["importGCTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ctrlToolChange {
            get {
                return ((bool)(this["ctrlToolChange"]));
            }
            set {
                this["ctrlToolChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_misc\\script_pen_pickup.nc")]
        public string ctrlToolScriptGet {
            get {
                return ((string)(this["ctrlToolScriptGet"]));
            }
            set {
                this["ctrlToolScriptGet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useSerial2 {
            get {
                return ((bool)(this["useSerial2"]));
            }
            set {
                this["useSerial2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_misc\\script_pen_remove.nc")]
        public string ctrlToolScriptPut {
            get {
                return ((string)(this["ctrlToolScriptPut"]));
            }
            set {
                this["ctrlToolScriptPut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_misc\\script_pen_select.nc")]
        public string ctrlToolScriptSelect {
            get {
                return ((string)(this["ctrlToolScriptSelect"]));
            }
            set {
                this["ctrlToolScriptSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importSVGToolSort {
            get {
                return ((bool)(this["importSVGToolSort"]));
            }
            set {
                this["importSVGToolSort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_misc\\script_probing_tool.nc")]
        public string ctrlToolScriptProbe {
            get {
                return ((string)(this["ctrlToolScriptProbe"]));
            }
            set {
                this["ctrlToolScriptProbe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_misc\\Stabilo_by_PN.gpl")]
        public string importPalette {
            get {
                return ((string)(this["importPalette"]));
            }
            set {
                this["importPalette"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal importGCDecPlaces {
            get {
                return ((decimal)(this["importGCDecPlaces"]));
            }
            set {
                this["importGCDecPlaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal joyXYStep1 {
            get {
                return ((decimal)(this["joyXYStep1"]));
            }
            set {
                this["joyXYStep1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public decimal joyXYStep2 {
            get {
                return ((decimal)(this["joyXYStep2"]));
            }
            set {
                this["joyXYStep2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal joyXYStep3 {
            get {
                return ((decimal)(this["joyXYStep3"]));
            }
            set {
                this["joyXYStep3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal joyXYStep4 {
            get {
                return ((decimal)(this["joyXYStep4"]));
            }
            set {
                this["joyXYStep4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal joyXYStep5 {
            get {
                return ((decimal)(this["joyXYStep5"]));
            }
            set {
                this["joyXYStep5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal joyXYSpeed1 {
            get {
                return ((decimal)(this["joyXYSpeed1"]));
            }
            set {
                this["joyXYSpeed1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal joyXYSpeed2 {
            get {
                return ((decimal)(this["joyXYSpeed2"]));
            }
            set {
                this["joyXYSpeed2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal joyXYSpeed3 {
            get {
                return ((decimal)(this["joyXYSpeed3"]));
            }
            set {
                this["joyXYSpeed3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public decimal joyXYSpeed4 {
            get {
                return ((decimal)(this["joyXYSpeed4"]));
            }
            set {
                this["joyXYSpeed4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal joyXYSpeed5 {
            get {
                return ((decimal)(this["joyXYSpeed5"]));
            }
            set {
                this["joyXYSpeed5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal joyZStep1 {
            get {
                return ((decimal)(this["joyZStep1"]));
            }
            set {
                this["joyZStep1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public decimal joyZStep2 {
            get {
                return ((decimal)(this["joyZStep2"]));
            }
            set {
                this["joyZStep2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal joyZStep3 {
            get {
                return ((decimal)(this["joyZStep3"]));
            }
            set {
                this["joyZStep3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal joyZStep4 {
            get {
                return ((decimal)(this["joyZStep4"]));
            }
            set {
                this["joyZStep4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal joyZStep5 {
            get {
                return ((decimal)(this["joyZStep5"]));
            }
            set {
                this["joyZStep5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal joyZSpeed1 {
            get {
                return ((decimal)(this["joyZSpeed1"]));
            }
            set {
                this["joyZSpeed1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal joyZSpeed2 {
            get {
                return ((decimal)(this["joyZSpeed2"]));
            }
            set {
                this["joyZSpeed2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal joyZSpeed3 {
            get {
                return ((decimal)(this["joyZSpeed3"]));
            }
            set {
                this["joyZSpeed3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public decimal joyZSpeed4 {
            get {
                return ((decimal)(this["joyZSpeed4"]));
            }
            set {
                this["joyZSpeed4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal joyZSpeed5 {
            get {
                return ((decimal)(this["joyZSpeed5"]));
            }
            set {
                this["joyZSpeed5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public decimal overrideFRTop {
            get {
                return ((decimal)(this["overrideFRTop"]));
            }
            set {
                this["overrideFRTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal overrideFRBtm {
            get {
                return ((decimal)(this["overrideFRBtm"]));
            }
            set {
                this["overrideFRBtm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int overrideFRValue {
            get {
                return ((int)(this["overrideFRValue"]));
            }
            set {
                this["overrideFRValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public decimal overrideSSTop {
            get {
                return ((decimal)(this["overrideSSTop"]));
            }
            set {
                this["overrideSSTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal overrideSSBtm {
            get {
                return ((decimal)(this["overrideSSBtm"]));
            }
            set {
                this["overrideSSBtm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int overrideSSValue {
            get {
                return ((int)(this["overrideSSValue"]));
            }
            set {
                this["overrideSSValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal toolDiameter {
            get {
                return ((decimal)(this["toolDiameter"]));
            }
            set {
                this["toolDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal toolZStep {
            get {
                return ((decimal)(this["toolZStep"]));
            }
            set {
                this["toolZStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public decimal toolFeedXY {
            get {
                return ((decimal)(this["toolFeedXY"]));
            }
            set {
                this["toolFeedXY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public decimal toolFeedZ {
            get {
                return ((decimal)(this["toolFeedZ"]));
            }
            set {
                this["toolFeedZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public decimal toolOverlap {
            get {
                return ((decimal)(this["toolOverlap"]));
            }
            set {
                this["toolOverlap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public decimal toolSpindleSpeed {
            get {
                return ((decimal)(this["toolSpindleSpeed"]));
            }
            set {
                this["toolSpindleSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public decimal shapeX {
            get {
                return ((decimal)(this["shapeX"]));
            }
            set {
                this["shapeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public decimal shapeY {
            get {
                return ((decimal)(this["shapeY"]));
            }
            set {
                this["shapeY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal shapeR {
            get {
                return ((decimal)(this["shapeR"]));
            }
            set {
                this["shapeR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int shapeType {
            get {
                return ((int)(this["shapeType"]));
            }
            set {
                this["shapeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int toolPath {
            get {
                return ((int)(this["toolPath"]));
            }
            set {
                this["toolPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int shapeOrigin {
            get {
                return ((int)(this["shapeOrigin"]));
            }
            set {
                this["shapeOrigin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importGCSpindleCmd {
            get {
                return ((bool)(this["importGCSpindleCmd"]));
            }
            set {
                this["importGCSpindleCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ctrlLaserMode {
            get {
                return ((bool)(this["ctrlLaserMode"]));
            }
            set {
                this["ctrlLaserMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ctrlReplaceEnable {
            get {
                return ((bool)(this["ctrlReplaceEnable"]));
            }
            set {
                this["ctrlReplaceEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ctrlReplaceM3 {
            get {
                return ((bool)(this["ctrlReplaceM3"]));
            }
            set {
                this["ctrlReplaceM3"] = value;
            }
        }
    }
}
