//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRBL_Plotter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string port {
            get {
                return ((string)(this["port"]));
            }
            set {
                this["port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public string baud {
            get {
                return ((string)(this["baud"]));
            }
            set {
                this["baud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\")]
        public string file {
            get {
                return ((string)(this["file"]));
            }
            set {
                this["file"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom Button 1||Nothing to do")]
        public string custom1 {
            get {
                return ((string)(this["custom1"]));
            }
            set {
                this["custom1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom Button 2||Nothing to do")]
        public string custom2 {
            get {
                return ((string)(this["custom2"]));
            }
            set {
                this["custom2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom Button 3||Nothing to do")]
        public string custom3 {
            get {
                return ((string)(this["custom3"]));
            }
            set {
                this["custom3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom Button 4||Nothing to do")]
        public string custom4 {
            get {
                return ((string)(this["custom4"]));
            }
            set {
                this["custom4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom Button 5||Nothing to do")]
        public string custom5 {
            get {
                return ((string)(this["custom5"]));
            }
            set {
                this["custom5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom Button 6||Nothing to do")]
        public string custom6 {
            get {
                return ((string)(this["custom6"]));
            }
            set {
                this["custom6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom Button 7||Nothing to do")]
        public string custom7 {
            get {
                return ((string)(this["custom7"]));
            }
            set {
                this["custom7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Custom Button 8||Nothing to do")]
        public string custom8 {
            get {
                return ((string)(this["custom8"]));
            }
            set {
                this["custom8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int camerindex {
            get {
                return ((int)(this["camerindex"]));
            }
            set {
                this["camerindex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public float camerarotation {
            get {
                return ((float)(this["camerarotation"]));
            }
            set {
                this["camerarotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double camerascalingTop {
            get {
                return ((double)(this["camerascalingTop"]));
            }
            set {
                this["camerascalingTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double camerascalingBot {
            get {
                return ((double)(this["camerascalingBot"]));
            }
            set {
                this["camerascalingBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double cameraTeachRadiusTop {
            get {
                return ((double)(this["cameraTeachRadiusTop"]));
            }
            set {
                this["cameraTeachRadiusTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double cameraTeachRadiusBot {
            get {
                return ((double)(this["cameraTeachRadiusBot"]));
            }
            set {
                this["cameraTeachRadiusBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cameraPosTop {
            get {
                return ((double)(this["cameraPosTop"]));
            }
            set {
                this["cameraPosTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-50")]
        public double cameraPosBot {
            get {
                return ((double)(this["cameraPosBot"]));
            }
            set {
                this["cameraPosBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cameraToolOffsetX {
            get {
                return ((double)(this["cameraToolOffsetX"]));
            }
            set {
                this["cameraToolOffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double cameraToolOffsetY {
            get {
                return ((double)(this["cameraToolOffsetY"]));
            }
            set {
                this["cameraToolOffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double lastOffsetX {
            get {
                return ((double)(this["lastOffsetX"]));
            }
            set {
                this["lastOffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double lastOffsetY {
            get {
                return ((double)(this["lastOffsetY"]));
            }
            set {
                this["lastOffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double lastOffsetZ {
            get {
                return ((double)(this["lastOffsetZ"]));
            }
            set {
                this["lastOffsetZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color colorBackground {
            get {
                return ((global::System.Drawing.Color)(this["colorBackground"]));
            }
            set {
                this["colorBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 192")]
        public global::System.Drawing.Color colorRuler {
            get {
                return ((global::System.Drawing.Color)(this["colorRuler"]));
            }
            set {
                this["colorRuler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color colorPenUp {
            get {
                return ((global::System.Drawing.Color)(this["colorPenUp"]));
            }
            set {
                this["colorPenUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color colorPenDown {
            get {
                return ((global::System.Drawing.Color)(this["colorPenDown"]));
            }
            set {
                this["colorPenDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color colorTool {
            get {
                return ((global::System.Drawing.Color)(this["colorTool"]));
            }
            set {
                this["colorTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal widthRuler {
            get {
                return ((decimal)(this["widthRuler"]));
            }
            set {
                this["widthRuler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public decimal widthPenUp {
            get {
                return ((decimal)(this["widthPenUp"]));
            }
            set {
                this["widthPenUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public decimal widthPenDown {
            get {
                return ((decimal)(this["widthPenDown"]));
            }
            set {
                this["widthPenDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public decimal widthTool {
            get {
                return ((decimal)(this["widthTool"]));
            }
            set {
                this["widthTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeepPink")]
        public global::System.Drawing.Color colorMarker {
            get {
                return ((global::System.Drawing.Color)(this["colorMarker"]));
            }
            set {
                this["colorMarker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal widthMarker {
            get {
                return ((decimal)(this["widthMarker"]));
            }
            set {
                this["widthMarker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int textFontIndex {
            get {
                return ((int)(this["textFontIndex"]));
            }
            set {
                this["textFontIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal textFontSize {
            get {
                return ((decimal)(this["textFontSize"]));
            }
            set {
                this["textFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal importGCZUp {
            get {
                return ((decimal)(this["importGCZUp"]));
            }
            set {
                this["importGCZUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2")]
        public decimal importGCZDown {
            get {
                return ((decimal)(this["importGCZDown"]));
            }
            set {
                this["importGCZDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal importGCZFeed {
            get {
                return ((decimal)(this["importGCZFeed"]));
            }
            set {
                this["importGCZFeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public decimal importGCSSpeed {
            get {
                return ((decimal)(this["importGCSSpeed"]));
            }
            set {
                this["importGCSSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test")]
        public string textFontText {
            get {
                return ((string)(this["textFontText"]));
            }
            set {
                this["textFontText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importGCZEnable {
            get {
                return ((bool)(this["importGCZEnable"]));
            }
            set {
                this["importGCZEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool importGCSpindleToggle {
            get {
                return ((bool)(this["importGCSpindleToggle"]));
            }
            set {
                this["importGCSpindleToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importGCAddComments {
            get {
                return ((bool)(this["importGCAddComments"]));
            }
            set {
                this["importGCAddComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public decimal importGCXYFeed {
            get {
                return ((decimal)(this["importGCXYFeed"]));
            }
            set {
                this["importGCXYFeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G21 G90")]
        public string importGCHeader {
            get {
                return ((string)(this["importGCHeader"]));
            }
            set {
                this["importGCHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G0 X0 Y0; M30")]
        public string importGCFooter {
            get {
                return ((string)(this["importGCFooter"]));
            }
            set {
                this["importGCFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool importGCPWMEnable {
            get {
                return ((bool)(this["importGCPWMEnable"]));
            }
            set {
                this["importGCPWMEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public decimal importGCPWMUp {
            get {
                return ((decimal)(this["importGCPWMUp"]));
            }
            set {
                this["importGCPWMUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public decimal importGCPWMDown {
            get {
                return ((decimal)(this["importGCPWMDown"]));
            }
            set {
                this["importGCPWMDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal importGCPWMDlyUp {
            get {
                return ((decimal)(this["importGCPWMDlyUp"]));
            }
            set {
                this["importGCPWMDlyUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal importGCPWMDlyDown {
            get {
                return ((decimal)(this["importGCPWMDlyDown"]));
            }
            set {
                this["importGCPWMDlyDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int importSVGBezier {
            get {
                return ((int)(this["importSVGBezier"]));
            }
            set {
                this["importSVGBezier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importSVGRezise {
            get {
                return ((bool)(this["importSVGRezise"]));
            }
            set {
                this["importSVGRezise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal importSVGMaxSize {
            get {
                return ((decimal)(this["importSVGMaxSize"]));
            }
            set {
                this["importSVGMaxSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importSVGAddComments {
            get {
                return ((bool)(this["importSVGAddComments"]));
            }
            set {
                this["importSVGAddComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importSVGReduce {
            get {
                return ((bool)(this["importSVGReduce"]));
            }
            set {
                this["importSVGReduce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal importSVGReduceLimit {
            get {
                return ((decimal)(this["importSVGReduceLimit"]));
            }
            set {
                this["importSVGReduceLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importSVGPauseElement {
            get {
                return ((bool)(this["importSVGPauseElement"]));
            }
            set {
                this["importSVGPauseElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importSVGPausePenDown {
            get {
                return ((bool)(this["importSVGPausePenDown"]));
            }
            set {
                this["importSVGPausePenDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool importSVGPathExtend {
            get {
                return ((bool)(this["importSVGPathExtend"]));
            }
            set {
                this["importSVGPathExtend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point locationSerForm {
            get {
                return ((global::System.Drawing.Point)(this["locationSerForm"]));
            }
            set {
                this["locationSerForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point locationMForm {
            get {
                return ((global::System.Drawing.Point)(this["locationMForm"]));
            }
            set {
                this["locationMForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point locationSetForm {
            get {
                return ((global::System.Drawing.Point)(this["locationSetForm"]));
            }
            set {
                this["locationSetForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point locationCamForm {
            get {
                return ((global::System.Drawing.Point)(this["locationCamForm"]));
            }
            set {
                this["locationCamForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool serialMinimize {
            get {
                return ((bool)(this["serialMinimize"]));
            }
            set {
                this["serialMinimize"] = value;
            }
        }
    }
}
