//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrblPlotter.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrblPlotter.Resources.ResStrings", typeof(ResStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distortion marker ähnelt.
        /// </summary>
        public static string cameraDistortionMarker {
            get {
                return ResourceManager.GetString("cameraDistortionMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for lower camera position ähnelt.
        /// </summary>
        public static string cameraForLowerPos {
            get {
                return ResourceManager.GetString("cameraForLowerPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for upper camera position ähnelt.
        /// </summary>
        public static string cameraForUpperPos {
            get {
                return ResourceManager.GetString("cameraForUpperPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fix mounted camera ähnelt.
        /// </summary>
        public static string cameraMountFix {
            get {
                return ResourceManager.GetString("cameraMountFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Camera mounted on XY platform ähnelt.
        /// </summary>
        public static string cameraMountXy {
            get {
                return ResourceManager.GetString("cameraMountXy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Camera mounted on Z axis ähnelt.
        /// </summary>
        public static string cameraMountXyz {
            get {
                return ResourceManager.GetString("cameraMountXyz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next click will teach scaling\r\n of camera view to ähnelt.
        /// </summary>
        public static string cameraNextClick {
            get {
                return ResourceManager.GetString("cameraNextClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No camera source found. Close and open this window after connecting a camera. ähnelt.
        /// </summary>
        public static string cameraNoCamera {
            get {
                return ResourceManager.GetString("cameraNoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press &apos;ESC&apos; to quit teaching. ähnelt.
        /// </summary>
        public static string cameraQuit {
            get {
                return ResourceManager.GetString("cameraQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die scaling ähnelt.
        /// </summary>
        public static string cameraScaling {
            get {
                return ResourceManager.GetString("cameraScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click to set cross hairs position ähnelt.
        /// </summary>
        public static string cameraSetCrossHairs {
            get {
                return ResourceManager.GetString("cameraSetCrossHairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teach four edges of the distorted rectangle (ratio 4:3). Press ESC to abort. ähnelt.
        /// </summary>
        public static string cameraSetDistortion {
            get {
                return ResourceManager.GetString("cameraSetDistortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set camera mounting to ähnelt.
        /// </summary>
        public static string cameraSetMount {
            get {
                return ResourceManager.GetString("cameraSetMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set radius ähnelt.
        /// </summary>
        public static string cameraSetRadius {
            get {
                return ResourceManager.GetString("cameraSetRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teach circle radius of ähnelt.
        /// </summary>
        public static string cameraTeachRadius {
            get {
                return ResourceManager.GetString("cameraTeachRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Given command is unknown or not supported, start an issue on github to clarify. ähnelt.
        /// </summary>
        public static string codeMessage_1_unknowncommand {
            get {
                return ResourceManager.GetString("codeMessage_1_unknowncommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layer, path or object is not visible because of visibility attribute. ähnelt.
        /// </summary>
        public static string codeMessage_1102_dontplot {
            get {
                return ResourceManager.GetString("codeMessage_1102_dontplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unsupported SVG-XML element was found.
        ///The resulting image may look different than expected.
        ///Possible workaround: try to convert object to path. ähnelt.
        /// </summary>
        public static string codeMessage_1103_elementsupport {
            get {
                return ResourceManager.GetString("codeMessage_1103_elementsupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unknown SVG-XML element was found.
        ///The resulting image may look different than expected.
        ///Possible workaround: try to convert object to path. ähnelt.
        /// </summary>
        public static string codeMessage_1104_elementuk {
            get {
                return ResourceManager.GetString("codeMessage_1104_elementuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An &apos;tspan&apos; element within a &apos;textPath&apos; element was found. This combination is not supported.
        ///The resulting image may look different than expected.
        ///Possible workaround: try to convert object to path. ähnelt.
        /// </summary>
        public static string codeMessage_1105_textpath {
            get {
                return ResourceManager.GetString("codeMessage_1105_textpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unsupported SVG-XML attribute was found.
        ///The resulting image may look different than expected.
        ///Possible workaround: try to convert object to path. ähnelt.
        /// </summary>
        public static string codeMessage_1106_attributesupport {
            get {
                return ResourceManager.GetString("codeMessage_1106_attributesupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layer is not visible or printing of layer is disabled. Check:
        ///https://librecad.readthedocs.io/en/latest/ref/widgets.html#widget-layerlist ähnelt.
        /// </summary>
        public static string codeMessage_1202_dontplot {
            get {
                return ResourceManager.GetString("codeMessage_1202_dontplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layer, path or object is not visible because of visibility attribute. ähnelt.
        /// </summary>
        public static string codeMessage_1302_dontplot {
            get {
                return ResourceManager.GetString("codeMessage_1302_dontplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string codeMessage_1x02_dontplot {
            get {
                return ResourceManager.GetString("codeMessage_1x02_dontplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The amount of single, selectable, figures exceeds the given maximum an would decrease the performance. \r\nAll figures are summarized to one figure.\r\nThe limit can be adjusted in\r\n[Setup - Graphics import - Path import - Grouping and tools - Conversion concerning] ähnelt.
        /// </summary>
        public static string codeMessage_2_highdataamount {
            get {
                return ResourceManager.GetString("codeMessage_2_highdataamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The z-axis is assigned twice: as tangential axis AND as Pen-up/down axis. \r\nThis will cause strange and unpredictable behavior. ähnelt.
        /// </summary>
        public static string codeMessage_2_zdoubletang {
            get {
                return ResourceManager.GetString("codeMessage_2_zdoubletang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die M3|M4 / M5 command will not be sent! -&gt; Spindle stays off. \r\nCheck option in \r\n[Setup - Graphics import - G-Code generation - Z axis Pen up/down translation] \r\n☐ Do not switch on spindle ähnelt.
        /// </summary>
        public static string codeMessage_3_spindlestaysoff {
            get {
                return ResourceManager.GetString("codeMessage_3_spindlestaysoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The z-axis is assigned twice: as auxillary axis AND as Pen-up/down axis. \r\nThis will cause strange and unpredictable behavior. ähnelt.
        /// </summary>
        public static string codeMessage_3_zdoubleaux {
            get {
                return ResourceManager.GetString("codeMessage_3_zdoubleaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The z-axis is assigned twice: as tangential axis AND as Pen-up/down axis. \r\nThis will cause strange and unpredictable behavior. ähnelt.
        /// </summary>
        public static string codeMessage_3_zdoubletang {
            get {
                return ResourceManager.GetString("codeMessage_3_zdoubletang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attention ähnelt.
        /// </summary>
        public static string codeMessage_attention {
            get {
                return ResourceManager.GetString("codeMessage_attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string codeMessage_error {
            get {
                return ResourceManager.GetString("codeMessage_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string codeMessage_warning {
            get {
                return ResourceManager.GetString("codeMessage_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm ähnelt.
        /// </summary>
        public static string grblAlarm {
            get {
                return ResourceManager.GetString("grblAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check ähnelt.
        /// </summary>
        public static string grblCheck {
            get {
                return ResourceManager.GetString("grblCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Door ähnelt.
        /// </summary>
        public static string grblDoor {
            get {
                return ResourceManager.GetString("grblDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hold ähnelt.
        /// </summary>
        public static string grblHold {
            get {
                return ResourceManager.GetString("grblHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string grblHome {
            get {
                return ResourceManager.GetString("grblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle ähnelt.
        /// </summary>
        public static string grblIdle {
            get {
                return ResourceManager.GetString("grblIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jog ähnelt.
        /// </summary>
        public static string grblJog {
            get {
                return ResourceManager.GetString("grblJog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die grbl controller is not connected!\r\nCannot perform the desired action! ähnelt.
        /// </summary>
        public static string grblNotConnected {
            get {
                return ResourceManager.GetString("grblNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Probe ähnelt.
        /// </summary>
        public static string grblProbe {
            get {
                return ResourceManager.GetString("grblProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run ähnelt.
        /// </summary>
        public static string grblRun {
            get {
                return ResourceManager.GetString("grblRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sleep ähnelt.
        /// </summary>
        public static string grblSleep {
            get {
                return ResourceManager.GetString("grblSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die height scan ähnelt.
        /// </summary>
        public static string heightScan {
            get {
                return ResourceManager.GetString("heightScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add imported graphic ähnelt.
        /// </summary>
        public static string importMessageAddGraphic {
            get {
                return ResourceManager.GetString("importMessageAddGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File name: ähnelt.
        /// </summary>
        public static string importMessageFileName {
            get {
                return ResourceManager.GetString("importMessageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File path: ähnelt.
        /// </summary>
        public static string importMessageFilePath {
            get {
                return ResourceManager.GetString("importMessageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GCode Footer ähnelt.
        /// </summary>
        public static string importMessageGcodeFooter {
            get {
                return ResourceManager.GetString("importMessageGcodeFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GCode Header ähnelt.
        /// </summary>
        public static string importMessageGcodeHeader {
            get {
                return ResourceManager.GetString("importMessageGcodeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General settings: ähnelt.
        /// </summary>
        public static string importMessageGeneralSettings {
            get {
                return ResourceManager.GetString("importMessageGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lasermode: use M3S0 instead of M5 to switch off laser (or spindle) ähnelt.
        /// </summary>
        public static string importMessageLaserMode {
            get {
                return ResourceManager.GetString("importMessageLaserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die grbl Laser mode $32 is not enabled ähnelt.
        /// </summary>
        public static string importMessageLaserModeNok {
            get {
                return ResourceManager.GetString("importMessageLaserModeNok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laser power ähnelt.
        /// </summary>
        public static string importMessageLaserPower {
            get {
                return ResourceManager.GetString("importMessageLaserPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die grbl X/Y Max. rate: ähnelt.
        /// </summary>
        public static string importMessageMaxXYFeed {
            get {
                return ResourceManager.GetString("importMessageMaxXYFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path interpretation: ähnelt.
        /// </summary>
        public static string importMessageOption1 {
            get {
                return ResourceManager.GetString("importMessageOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Possible path interpretations ähnelt.
        /// </summary>
        public static string importMessageOption1Link {
            get {
                return ResourceManager.GetString("importMessageOption1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path modification: ähnelt.
        /// </summary>
        public static string importMessageOption2 {
            get {
                return ResourceManager.GetString("importMessageOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Possible path modifications ähnelt.
        /// </summary>
        public static string importMessageOption2Link {
            get {
                return ResourceManager.GetString("importMessageOption2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convert circle-radius to Z value ähnelt.
        /// </summary>
        public static string importMessageOptionCircleRadiusToZ {
            get {
                return ResourceManager.GetString("importMessageOptionCircleRadiusToZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convert circle to point ähnelt.
        /// </summary>
        public static string importMessageOptionCircleToDot {
            get {
                return ResourceManager.GetString("importMessageOptionCircleToDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crop or tile graphic ähnelt.
        /// </summary>
        public static string importMessageOptionClip {
            get {
                return ResourceManager.GetString("importMessageOptionClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adapt path for Drag tool ähnelt.
        /// </summary>
        public static string importMessageOptionDragTool {
            get {
                return ResourceManager.GetString("importMessageOptionDragTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extend path (e.g. for laser cutting) ähnelt.
        /// </summary>
        public static string importMessageOptionExtend {
            get {
                return ResourceManager.GetString("importMessageOptionExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter graphic elements (remove objects) ähnelt.
        /// </summary>
        public static string importMessageOptionFilter {
            get {
                return ResourceManager.GetString("importMessageOptionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Hatch fill ähnelt.
        /// </summary>
        public static string importMessageOptionHatchFill {
            get {
                return ResourceManager.GetString("importMessageOptionHatchFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nodes only - make dots at given coordinates ähnelt.
        /// </summary>
        public static string importMessageOptionNodesOnly {
            get {
                return ResourceManager.GetString("importMessageOptionNodesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outline development ähnelt.
        /// </summary>
        public static string importMessageOptionOutlineDevelop {
            get {
                return ResourceManager.GetString("importMessageOptionOutlineDevelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get S value from line width (laser power / spindle speed) ähnelt.
        /// </summary>
        public static string importMessageOptionSFromWidth {
            get {
                return ResourceManager.GetString("importMessageOptionSFromWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tangential axis ähnelt.
        /// </summary>
        public static string importMessageOptionTangential {
            get {
                return ResourceManager.GetString("importMessageOptionTangential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wire bender ähnelt.
        /// </summary>
        public static string importMessageOptionWireBender {
            get {
                return ResourceManager.GetString("importMessageOptionWireBender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Z value from line width (depth) ähnelt.
        /// </summary>
        public static string importMessageOptionZFromWidth {
            get {
                return ResourceManager.GetString("importMessageOptionZFromWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pen up/down translation: ähnelt.
        /// </summary>
        public static string importMessagePUD {
            get {
                return ResourceManager.GetString("importMessagePUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Individual commands ähnelt.
        /// </summary>
        public static string importMessagePUDIndividual {
            get {
                return ResourceManager.GetString("importMessagePUDIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pen Down ähnelt.
        /// </summary>
        public static string importMessagePUDPenDown {
            get {
                return ResourceManager.GetString("importMessagePUDPenDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pen Up ähnelt.
        /// </summary>
        public static string importMessagePUDPenUp {
            get {
                return ResourceManager.GetString("importMessagePUDPenUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PWM enabled (Servo control) ähnelt.
        /// </summary>
        public static string importMessagePUDPWM {
            get {
                return ResourceManager.GetString("importMessagePUDPWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PWM Down ähnelt.
        /// </summary>
        public static string importMessagePUDPWMDown {
            get {
                return ResourceManager.GetString("importMessagePUDPWMDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PWM Up ähnelt.
        /// </summary>
        public static string importMessagePUDPWMUp {
            get {
                return ResourceManager.GetString("importMessagePUDPWMUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PWM Zero ähnelt.
        /// </summary>
        public static string importMessagePUDPWMZero {
            get {
                return ResourceManager.GetString("importMessagePUDPWMZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spindle on/off with Pen down/up ähnelt.
        /// </summary>
        public static string importMessagePUDSpindle {
            get {
                return ResourceManager.GetString("importMessagePUDSpindle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Z axis enabled ähnelt.
        /// </summary>
        public static string importMessagePUDZ {
            get {
                return ResourceManager.GetString("importMessagePUDZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depth per pass ähnelt.
        /// </summary>
        public static string importMessagePUDZDepthPass {
            get {
                return ResourceManager.GetString("importMessagePUDZDepthPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Z up between passes ähnelt.
        /// </summary>
        public static string importMessagePUDZDepthPassNoZUp {
            get {
                return ResourceManager.GetString("importMessagePUDZDepthPassNoZUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Z Down (engrave) ähnelt.
        /// </summary>
        public static string importMessagePUDZDown {
            get {
                return ResourceManager.GetString("importMessagePUDZDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Z Feed ähnelt.
        /// </summary>
        public static string importMessagePUDZFeed {
            get {
                return ResourceManager.GetString("importMessagePUDZFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die grbl Z Max. Feed rate: ähnelt.
        /// </summary>
        public static string importMessagePUDZFeedMax {
            get {
                return ResourceManager.GetString("importMessagePUDZFeedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spindle will not be switched on ähnelt.
        /// </summary>
        public static string importMessagePUDZNoSpindle {
            get {
                return ResourceManager.GetString("importMessagePUDZNoSpindle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Z Up (save) ähnelt.
        /// </summary>
        public static string importMessagePUDZUp {
            get {
                return ResourceManager.GetString("importMessagePUDZUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Relative movements are enabled ähnelt.
        /// </summary>
        public static string importMessageRelMovement {
            get {
                return ResourceManager.GetString("importMessageRelMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From Metadata ähnelt.
        /// </summary>
        public static string importMessageSourceMetadata {
            get {
                return ResourceManager.GetString("importMessageSourceMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From tool table ähnelt.
        /// </summary>
        public static string importMessageSourceTooltable {
            get {
                return ResourceManager.GetString("importMessageSourceTooltable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laser mode / Spindle direction ähnelt.
        /// </summary>
        public static string importMessageSpindleDirection {
            get {
                return ResourceManager.GetString("importMessageSpindleDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die M3 (CW-clockwise) Constant Laser Power Mode ähnelt.
        /// </summary>
        public static string importMessageSpindleDirectionM3 {
            get {
                return ResourceManager.GetString("importMessageSpindleDirectionM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die M4 (CCW-counterclockwise) Dynamic Laser Power Mode ähnelt.
        /// </summary>
        public static string importMessageSpindleDirectionM4 {
            get {
                return ResourceManager.GetString("importMessageSpindleDirectionM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spindle Speed ähnelt.
        /// </summary>
        public static string importMessageSpindleSpeed {
            get {
                return ResourceManager.GetString("importMessageSpindleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die grbl Spindle speed Max. ähnelt.
        /// </summary>
        public static string importMessageSpindleSpeedMax {
            get {
                return ResourceManager.GetString("importMessageSpindleSpeedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SVG Metadata available, but not enabled! ähnelt.
        /// </summary>
        public static string importMessageSVGMetaDataNok1 {
            get {
                return ResourceManager.GetString("importMessageSVGMetaDataNok1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SVG Metadata processed ähnelt.
        /// </summary>
        public static string importMessageSVGMetaDataOk {
            get {
                return ResourceManager.GetString("importMessageSVGMetaDataOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import information ähnelt.
        /// </summary>
        public static string importMessageTitle {
            get {
                return ResourceManager.GetString("importMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tool table needed, last loaded: ähnelt.
        /// </summary>
        public static string importMessageToolTableNeeded {
            get {
                return ResourceManager.GetString("importMessageToolTableNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XY Feed ähnelt.
        /// </summary>
        public static string importMessageXYFeed {
            get {
                return ResourceManager.GetString("importMessageXYFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue last job? ähnelt.
        /// </summary>
        public static string loadMessageContinue {
            get {
                return ResourceManager.GetString("loadMessageContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading the last processed G-Code ähnelt.
        /// </summary>
        public static string loadMessageLastProcessed {
            get {
                return ResourceManager.GetString("loadMessageLastProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading G-Code ähnelt.
        /// </summary>
        public static string loadMessageLoad1 {
            get {
                return ResourceManager.GetString("loadMessageLoad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No import options applied! ähnelt.
        /// </summary>
        public static string loadMessageNoImport {
            get {
                return ResourceManager.GetString("loadMessageNoImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load G-Code option: Replaces laser mode command M3 by M4 ähnelt.
        /// </summary>
        public static string loadMessageReplaceM34 {
            get {
                return ResourceManager.GetString("loadMessageReplaceM34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load G-Code option: Replaces laser mode command M4 by M3 ähnelt.
        /// </summary>
        public static string loadMessageReplaceM43 {
            get {
                return ResourceManager.GetString("loadMessageReplaceM43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Streaming is active, can&apos;t load new file. ähnelt.
        /// </summary>
        public static string loadMessageStreaming {
            get {
                return ResourceManager.GetString("loadMessageStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic tool change is enabled ähnelt.
        /// </summary>
        public static string loadMessageToolChange {
            get {
                return ResourceManager.GetString("loadMessageToolChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attention ähnelt.
        /// </summary>
        public static string mainAttention {
            get {
                return ResourceManager.GetString("mainAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feel free to improove translation ähnelt.
        /// </summary>
        public static string mainHelpLanguage {
            get {
                return ResourceManager.GetString("mainHelpLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File &apos;hotkeys.xml&apos; not found, no hotkeys set! ähnelt.
        /// </summary>
        public static string mainHotkeyError {
            get {
                return ResourceManager.GetString("mainHotkeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown action: ähnelt.
        /// </summary>
        public static string mainHotkeyError1 {
            get {
                return ResourceManager.GetString("mainHotkeyError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error with Hotkey.xml ähnelt.
        /// </summary>
        public static string mainHotkeyError2 {
            get {
                return ResourceManager.GetString("mainHotkeyError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check G-Code ähnelt.
        /// </summary>
        public static string mainInfoCheckCode {
            get {
                return ResourceManager.GetString("mainInfoCheckCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error before line ähnelt.
        /// </summary>
        public static string mainInfoErrorLine {
            get {
                return ResourceManager.GetString("mainInfoErrorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish checking G-Code ähnelt.
        /// </summary>
        public static string mainInfoFinishCheck {
            get {
                return ResourceManager.GetString("mainInfoFinishCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish sending G-Code ähnelt.
        /// </summary>
        public static string mainInfoFinishSend {
            get {
                return ResourceManager.GetString("mainInfoFinishSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press &apos;Kill Alarm&apos; to proceed (&apos;$X&apos;) ähnelt.
        /// </summary>
        public static string mainInfoKill {
            get {
                return ResourceManager.GetString("mainInfoKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laser Mode not active $32=0 ähnelt.
        /// </summary>
        public static string mainInfoLaserModeOff {
            get {
                return ResourceManager.GetString("mainInfoLaserModeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laser Mode active $32=1 ähnelt.
        /// </summary>
        public static string mainInfoLaserModeOn {
            get {
                return ResourceManager.GetString("mainInfoLaserModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause streaming - press play ( ähnelt.
        /// </summary>
        public static string mainInfoPause {
            get {
                return ResourceManager.GetString("mainInfoPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Probing ähnelt.
        /// </summary>
        public static string mainInfoProbing {
            get {
                return ResourceManager.GetString("mainInfoProbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press &apos;Resume&apos; to proceed ähnelt.
        /// </summary>
        public static string mainInfoResume {
            get {
                return ResourceManager.GetString("mainInfoResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send G-Code ähnelt.
        /// </summary>
        public static string mainInfoSendCode {
            get {
                return ResourceManager.GetString("mainInfoSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STOP streaming ( ähnelt.
        /// </summary>
        public static string mainInfoStopStream {
            get {
                return ResourceManager.GetString("mainInfoStopStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STOP streaming ( Line ähnelt.
        /// </summary>
        public static string mainInfoStopStream2 {
            get {
                return ResourceManager.GetString("mainInfoStopStream2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tool change... ähnelt.
        /// </summary>
        public static string mainInfoToolChange {
            get {
                return ResourceManager.GetString("mainInfoToolChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo last action ähnelt.
        /// </summary>
        public static string mainInfoUndo {
            get {
                return ResourceManager.GetString("mainInfoUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wait for IDLE, then pause ( ähnelt.
        /// </summary>
        public static string mainInfoWaitIdle {
            get {
                return ResourceManager.GetString("mainInfoWaitIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next move will exceed machine limits!\r ähnelt.
        /// </summary>
        public static string mainLimits1 {
            get {
                return ResourceManager.GetString("mainLimits1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \r\n Press &apos;Ok&apos; to move anyway ähnelt.
        /// </summary>
        public static string mainLimits2 {
            get {
                return ResourceManager.GetString("mainLimits2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphics dimension exceeds machine dimension!\r\nTransformation is recommended to avoid damaging the machine! ähnelt.
        /// </summary>
        public static string mainLimits3 {
            get {
                return ResourceManager.GetString("mainLimits3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Streaming must be stopped before loading new file ähnelt.
        /// </summary>
        public static string mainLoadError {
            get {
                return ResourceManager.GetString("mainLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File not found: &apos; ähnelt.
        /// </summary>
        public static string mainLoadError1 {
            get {
                return ResourceManager.GetString("mainLoadError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL extension is not &apos;svg&apos; or &apos;dxf&apos;\r\nTry SVG import anyway, but without setting &apos;Recent File&apos; list. ähnelt.
        /// </summary>
        public static string mainLoadError2 {
            get {
                return ResourceManager.GetString("mainLoadError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File extension not supported &apos; ähnelt.
        /// </summary>
        public static string mainLoadError3 {
            get {
                return ResourceManager.GetString("mainLoadError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not a valid number ähnelt.
        /// </summary>
        public static string mainParseError {
            get {
                return ResourceManager.GetString("mainParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not a valid number, set line to 0 ähnelt.
        /// </summary>
        public static string mainParseError1 {
            get {
                return ResourceManager.GetString("mainParseError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause streaming - press play ähnelt.
        /// </summary>
        public static string mainPauseStream {
            get {
                return ResourceManager.GetString("mainPauseStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last job was paused at line ähnelt.
        /// </summary>
        public static string mainPauseStream1 {
            get {
                return ResourceManager.GetString("mainPauseStream1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to continue the job? ähnelt.
        /// </summary>
        public static string mainPauseStream2 {
            get {
                return ResourceManager.GetString("mainPauseStream2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem ähnelt.
        /// </summary>
        public static string mainProblem {
            get {
                return ResourceManager.GetString("mainProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progress ähnelt.
        /// </summary>
        public static string mainProgress {
            get {
                return ResourceManager.GetString("mainProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit GRBL-Plotter? ähnelt.
        /// </summary>
        public static string mainQuit {
            get {
                return ResourceManager.GetString("mainQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ähnelt.
        /// </summary>
        public static string mainSimuSpeed {
            get {
                return ResourceManager.GetString("mainSimuSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start path simulation ähnelt.
        /// </summary>
        public static string mainSimuStart {
            get {
                return ResourceManager.GetString("mainSimuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop simulation ähnelt.
        /// </summary>
        public static string mainSimuStop {
            get {
                return ResourceManager.GetString("mainSimuStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing program files,&lt;br&gt;please check the GRBL-Plotter installation ähnelt.
        /// </summary>
        public static string mainStartMissingFiles {
            get {
                return ResourceManager.GetString("mainStartMissingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Streaming is still active - press Stop and try again ähnelt.
        /// </summary>
        public static string mainStreamingActive {
            get {
                return ResourceManager.GetString("mainStreamingActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tool / Pen change! ähnelt.
        /// </summary>
        public static string mainToolChange {
            get {
                return ResourceManager.GetString("mainToolChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tool change needed:\r ähnelt.
        /// </summary>
        public static string mainToolChange1 {
            get {
                return ResourceManager.GetString("mainToolChange1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \rpress start to continue. ähnelt.
        /// </summary>
        public static string mainToolChange2 {
            get {
                return ResourceManager.GetString("mainToolChange2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fixed some unknown G-Code:\r\n ähnelt.
        /// </summary>
        public static string mainUnknownCode {
            get {
                return ResourceManager.GetString("mainUnknownCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string NewKey {
            get {
                return ResourceManager.GetString("NewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die probing ähnelt.
        /// </summary>
        public static string probing {
            get {
                return ResourceManager.GetString("probing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Probing canceled ähnelt.
        /// </summary>
        public static string probingCancel1 {
            get {
                return ResourceManager.GetString("probingCancel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process last command ähnelt.
        /// </summary>
        public static string probingCancel2 {
            get {
                return ResourceManager.GetString("probingCancel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move to center ähnelt.
        /// </summary>
        public static string probingCenter {
            get {
                return ResourceManager.GetString("probingCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fail: no contact ähnelt.
        /// </summary>
        public static string probingFail1 {
            get {
                return ResourceManager.GetString("probingFail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel probing ähnelt.
        /// </summary>
        public static string probingFail2 {
            get {
                return ResourceManager.GetString("probingFail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish ähnelt.
        /// </summary>
        public static string probingFinish {
            get {
                return ResourceManager.GetString("probingFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Probing on ähnelt.
        /// </summary>
        public static string probingProbingOn {
            get {
                return ResourceManager.GetString("probingProbingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set center  ähnelt.
        /// </summary>
        public static string probingSetCenter {
            get {
                return ResourceManager.GetString("probingSetCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time out ähnelt.
        /// </summary>
        public static string probingTimeOut {
            get {
                return ResourceManager.GetString("probingTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die scan ähnelt.
        /// </summary>
        public static string scan {
            get {
                return ResourceManager.GetString("scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string serialClose {
            get {
                return ResourceManager.GetString("serialClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serial Connection is needed.\r\nClose main window instead ähnelt.
        /// </summary>
        public static string serialCloseError {
            get {
                return ResourceManager.GetString("serialCloseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string serialOpen {
            get {
                return ResourceManager.GetString("serialOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom button is blocked while streaming ähnelt.
        /// </summary>
        public static string statusStripeButtonBlocked {
            get {
                return ResourceManager.GetString("statusStripeButtonBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check COM-window for further information ähnelt.
        /// </summary>
        public static string statusStripeCheckCOM {
            get {
                return ResourceManager.GetString("statusStripeCheckCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;Check for new GRBL-Plotter release on GitHub&apos; - can be disabled in [Setup - Program control]  ähnelt.
        /// </summary>
        public static string statusStripeCheckUpdate {
            get {
                return ResourceManager.GetString("statusStripeCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alt-Click to select Figure; Control-Click to select Group; Shift-Click to select Tile;Or click on XML-Tag ähnelt.
        /// </summary>
        public static string statusStripeClickKeys {
            get {
                return ResourceManager.GetString("statusStripeClickKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click: mark Figure; Control-Click: mark Group; Shift-Click: mark Tile;Alt-Click: show GCode line ähnelt.
        /// </summary>
        public static string statusStripeClickKeys2 {
            get {
                return ResourceManager.GetString("statusStripeClickKeys2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control-Down to move selected Block one down; Control-Shift-Down to move to end ähnelt.
        /// </summary>
        public static string statusStripeDownKeys {
            get {
                return ResourceManager.GetString("statusStripeDownKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit mode on - click into 2D view to finish ähnelt.
        /// </summary>
        public static string statusStripeEditModeOn {
            get {
                return ResourceManager.GetString("statusStripeEditModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File loading ähnelt.
        /// </summary>
        public static string statusStripeFileLoad {
            get {
                return ResourceManager.GetString("statusStripeFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File not found - remove from list ähnelt.
        /// </summary>
        public static string statusStripeFileNotFound {
            get {
                return ResourceManager.GetString("statusStripeFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Perhaps serial port is locked and a restart of GRBL-Plotter is needed ähnelt.
        /// </summary>
        public static string statusStripeGrblResetNeeded {
            get {
                return ResourceManager.GetString("statusStripeGrblResetNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Probably a reset of the controller is needed ähnelt.
        /// </summary>
        public static string statusStripeResetNeeded {
            get {
                return ResourceManager.GetString("statusStripeResetNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection moved by ähnelt.
        /// </summary>
        public static string statusStripeSelectionMoved {
            get {
                return ResourceManager.GetString("statusStripeSelectionMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check G-Code on grbl controller ähnelt.
        /// </summary>
        public static string statusStripeStreamingCheck {
            get {
                return ResourceManager.GetString("statusStripeStreamingCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue streaming ähnelt.
        /// </summary>
        public static string statusStripeStreamingContinue {
            get {
                return ResourceManager.GetString("statusStripeStreamingContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Streaming FINISHED after ähnelt.
        /// </summary>
        public static string statusStripeStreamingFinish {
            get {
                return ResourceManager.GetString("statusStripeStreamingFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Streaming PAUSE ähnelt.
        /// </summary>
        public static string statusStripeStreamingPause {
            get {
                return ResourceManager.GetString("statusStripeStreamingPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Streaming START from line ähnelt.
        /// </summary>
        public static string statusStripeStreamingStart {
            get {
                return ResourceManager.GetString("statusStripeStreamingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Streaming status and G-Code are saved in &apos;_lastProcessed.nc&apos;. Continuation after program restart is possible. ähnelt.
        /// </summary>
        public static string statusStripeStreamingStatusSaved {
            get {
                return ResourceManager.GetString("statusStripeStreamingStatusSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Streaming STOP at line ähnelt.
        /// </summary>
        public static string statusStripeStreamingStop {
            get {
                return ResourceManager.GetString("statusStripeStreamingStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control-Up to move selected Block one up; Control-Shift-Up to move to top ähnelt.
        /// </summary>
        public static string statusStripeUpKeys {
            get {
                return ResourceManager.GetString("statusStripeUpKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use current settings (last loaded: &apos;{0}&apos;) ähnelt.
        /// </summary>
        public static string useCaseHeader1 {
            get {
                return ResourceManager.GetString("useCaseHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings from &apos;{0}&apos; ähnelt.
        /// </summary>
        public static string useCaseHeader2 {
            get {
                return ResourceManager.GetString("useCaseHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A use-case is a presetted setup to adjust settings for a specific machine and/or application.\r\nThe settings of a selected and applied use-case also remain after the import of the graphics.\r\nA use-case needs to be stored in \data\usecases to be accessible.\r\nAlso exported machine-settings and sub-sets of it can be used. ähnelt.
        /// </summary>
        public static string useCaseInfo {
            get {
                return ResourceManager.GetString("useCaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string useCaseInfo2 {
            get {
                return ResourceManager.GetString("useCaseInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ### Current settings ### ähnelt.
        /// </summary>
        public static string useCaseItem0 {
            get {
                return ResourceManager.GetString("useCaseItem0", resourceCulture);
            }
        }
    }
}
