//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrblPlotter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrblPlotter.Resources.ResStrings", typeof(ResStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distortion marker.
        /// </summary>
        public static string cameraDistortionMarker {
            get {
                return ResourceManager.GetString("cameraDistortionMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for lower camera position.
        /// </summary>
        public static string cameraForLowerPos {
            get {
                return ResourceManager.GetString("cameraForLowerPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for upper camera position.
        /// </summary>
        public static string cameraForUpperPos {
            get {
                return ResourceManager.GetString("cameraForUpperPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix mounted camera.
        /// </summary>
        public static string cameraMountFix {
            get {
                return ResourceManager.GetString("cameraMountFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera mounted on XY platform.
        /// </summary>
        public static string cameraMountXy {
            get {
                return ResourceManager.GetString("cameraMountXy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera mounted on Z axis.
        /// </summary>
        public static string cameraMountXyz {
            get {
                return ResourceManager.GetString("cameraMountXyz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next click will teach scaling\r\n of camera view to.
        /// </summary>
        public static string cameraNextClick {
            get {
                return ResourceManager.GetString("cameraNextClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No camera source found. Close and open this window after connecting a camera..
        /// </summary>
        public static string cameraNoCamera {
            get {
                return ResourceManager.GetString("cameraNoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;ESC&apos; to quit teaching..
        /// </summary>
        public static string cameraQuit {
            get {
                return ResourceManager.GetString("cameraQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scaling.
        /// </summary>
        public static string cameraScaling {
            get {
                return ResourceManager.GetString("cameraScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set cross hairs position.
        /// </summary>
        public static string cameraSetCrossHairs {
            get {
                return ResourceManager.GetString("cameraSetCrossHairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teach four edges of the distorted rectangle (ratio 4:3). Press ESC to abort..
        /// </summary>
        public static string cameraSetDistortion {
            get {
                return ResourceManager.GetString("cameraSetDistortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set camera mounting to.
        /// </summary>
        public static string cameraSetMount {
            get {
                return ResourceManager.GetString("cameraSetMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set radius.
        /// </summary>
        public static string cameraSetRadius {
            get {
                return ResourceManager.GetString("cameraSetRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teach circle radius of.
        /// </summary>
        public static string cameraTeachRadius {
            get {
                return ResourceManager.GetString("cameraTeachRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given command is unknown or not supported, start an issue on github to clarify..
        /// </summary>
        public static string codeMessage_1_unknowncommand {
            get {
                return ResourceManager.GetString("codeMessage_1_unknowncommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer is not visible or printing of layer is disabled. Check:
        ///https://librecad.readthedocs.io/en/latest/ref/widgets.html#widget-layerlist.
        /// </summary>
        public static string codeMessage_1202_dontplot {
            get {
                return ResourceManager.GetString("codeMessage_1202_dontplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer, path or object is not visible because of visibility attribute..
        /// </summary>
        public static string codeMessage_1302_dontplot {
            get {
                return ResourceManager.GetString("codeMessage_1302_dontplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string codeMessage_1x02_dontplot {
            get {
                return ResourceManager.GetString("codeMessage_1x02_dontplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of single, selectable, figures exceeds the given maximum an would decrease the performance. \r\nAll figures are summarized to one figure.\r\nThe limit can be adjusted in\r\n[Setup - Graphics import - Path import - Grouping and tools - Concersion concerning].
        /// </summary>
        public static string codeMessage_2_highdataamount {
            get {
                return ResourceManager.GetString("codeMessage_2_highdataamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The z-axis is assigned twice: as tangential axis AND as Pen-up/down axis. \r\nThis will cause strange and unpredictable behavior..
        /// </summary>
        public static string codeMessage_2_zdoubletang {
            get {
                return ResourceManager.GetString("codeMessage_2_zdoubletang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3|M4 / M5 command will not be sent! -&gt; Spindle stays off. \r\nCheck option in \r\n[Setup - Graphics import - G-Code generation - Z axis Pen up/down translation] \r\n☐ Do not switch on spindle.
        /// </summary>
        public static string codeMessage_3_spindlestaysoff {
            get {
                return ResourceManager.GetString("codeMessage_3_spindlestaysoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The z-axis is assigned twice: as auxillary axis AND as Pen-up/down axis. \r\nThis will cause strange and unpredictable behavior..
        /// </summary>
        public static string codeMessage_3_zdoubleaux {
            get {
                return ResourceManager.GetString("codeMessage_3_zdoubleaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The z-axis is assigned twice: as tangential axis AND as Pen-up/down axis. \r\nThis will cause strange and unpredictable behavior..
        /// </summary>
        public static string codeMessage_3_zdoubletang {
            get {
                return ResourceManager.GetString("codeMessage_3_zdoubletang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string codeMessage_attention {
            get {
                return ResourceManager.GetString("codeMessage_attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string codeMessage_error {
            get {
                return ResourceManager.GetString("codeMessage_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string codeMessage_warning {
            get {
                return ResourceManager.GetString("codeMessage_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string grblAlarm {
            get {
                return ResourceManager.GetString("grblAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string grblCheck {
            get {
                return ResourceManager.GetString("grblCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string grblDoor {
            get {
                return ResourceManager.GetString("grblDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string grblHold {
            get {
                return ResourceManager.GetString("grblHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string grblHome {
            get {
                return ResourceManager.GetString("grblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string grblIdle {
            get {
                return ResourceManager.GetString("grblIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jog.
        /// </summary>
        public static string grblJog {
            get {
                return ResourceManager.GetString("grblJog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grbl controller is not connected!\r\nCannot perform the desired action!.
        /// </summary>
        public static string grblNotConnected {
            get {
                return ResourceManager.GetString("grblNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe.
        /// </summary>
        public static string grblProbe {
            get {
                return ResourceManager.GetString("grblProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string grblRun {
            get {
                return ResourceManager.GetString("grblRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string grblSleep {
            get {
                return ResourceManager.GetString("grblSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to height scan.
        /// </summary>
        public static string heightScan {
            get {
                return ResourceManager.GetString("heightScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string mainAttention {
            get {
                return ResourceManager.GetString("mainAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to improove translation.
        /// </summary>
        public static string mainHelpLanguage {
            get {
                return ResourceManager.GetString("mainHelpLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;hotkeys.xml&apos; not found, no hotkeys set!.
        /// </summary>
        public static string mainHotkeyError {
            get {
                return ResourceManager.GetString("mainHotkeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown action:.
        /// </summary>
        public static string mainHotkeyError1 {
            get {
                return ResourceManager.GetString("mainHotkeyError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with Hotkey.xml.
        /// </summary>
        public static string mainHotkeyError2 {
            get {
                return ResourceManager.GetString("mainHotkeyError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check G-Code.
        /// </summary>
        public static string mainInfoCheckCode {
            get {
                return ResourceManager.GetString("mainInfoCheckCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error before line.
        /// </summary>
        public static string mainInfoErrorLine {
            get {
                return ResourceManager.GetString("mainInfoErrorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish checking G-Code.
        /// </summary>
        public static string mainInfoFinishCheck {
            get {
                return ResourceManager.GetString("mainInfoFinishCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish sending G-Code.
        /// </summary>
        public static string mainInfoFinishSend {
            get {
                return ResourceManager.GetString("mainInfoFinishSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Kill Alarm&apos; to proceed (&apos;$X&apos;).
        /// </summary>
        public static string mainInfoKill {
            get {
                return ResourceManager.GetString("mainInfoKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Mode not active $32=0.
        /// </summary>
        public static string mainInfoLaserModeOff {
            get {
                return ResourceManager.GetString("mainInfoLaserModeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Mode active $32=1.
        /// </summary>
        public static string mainInfoLaserModeOn {
            get {
                return ResourceManager.GetString("mainInfoLaserModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause streaming - press play (.
        /// </summary>
        public static string mainInfoPause {
            get {
                return ResourceManager.GetString("mainInfoPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing.
        /// </summary>
        public static string mainInfoProbing {
            get {
                return ResourceManager.GetString("mainInfoProbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Resume&apos; to proceed.
        /// </summary>
        public static string mainInfoResume {
            get {
                return ResourceManager.GetString("mainInfoResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send G-Code.
        /// </summary>
        public static string mainInfoSendCode {
            get {
                return ResourceManager.GetString("mainInfoSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP streaming (.
        /// </summary>
        public static string mainInfoStopStream {
            get {
                return ResourceManager.GetString("mainInfoStopStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP streaming ( Line.
        /// </summary>
        public static string mainInfoStopStream2 {
            get {
                return ResourceManager.GetString("mainInfoStopStream2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool change....
        /// </summary>
        public static string mainInfoToolChange {
            get {
                return ResourceManager.GetString("mainInfoToolChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last action.
        /// </summary>
        public static string mainInfoUndo {
            get {
                return ResourceManager.GetString("mainInfoUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for IDLE, then pause (.
        /// </summary>
        public static string mainInfoWaitIdle {
            get {
                return ResourceManager.GetString("mainInfoWaitIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next move will exceed machine limits!\r.
        /// </summary>
        public static string mainLimits1 {
            get {
                return ResourceManager.GetString("mainLimits1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n Press &apos;Ok&apos; to move anyway.
        /// </summary>
        public static string mainLimits2 {
            get {
                return ResourceManager.GetString("mainLimits2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics dimension exceeds machine dimension!\r\nTransformation is recommended to avoid damaging the machine!.
        /// </summary>
        public static string mainLimits3 {
            get {
                return ResourceManager.GetString("mainLimits3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming must be stopped before loading new file.
        /// </summary>
        public static string mainLoadError {
            get {
                return ResourceManager.GetString("mainLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: &apos;.
        /// </summary>
        public static string mainLoadError1 {
            get {
                return ResourceManager.GetString("mainLoadError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL extension is not &apos;svg&apos; or &apos;dxf&apos;\r\nTry SVG import anyway, but without setting &apos;Recent File&apos; list..
        /// </summary>
        public static string mainLoadError2 {
            get {
                return ResourceManager.GetString("mainLoadError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension not supported &apos;.
        /// </summary>
        public static string mainLoadError3 {
            get {
                return ResourceManager.GetString("mainLoadError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid number.
        /// </summary>
        public static string mainParseError {
            get {
                return ResourceManager.GetString("mainParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid number, set line to 0.
        /// </summary>
        public static string mainParseError1 {
            get {
                return ResourceManager.GetString("mainParseError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause streaming - press play.
        /// </summary>
        public static string mainPauseStream {
            get {
                return ResourceManager.GetString("mainPauseStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last job was paused at line.
        /// </summary>
        public static string mainPauseStream1 {
            get {
                return ResourceManager.GetString("mainPauseStream1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,\r\ndo you want to continue the job?.
        /// </summary>
        public static string mainPauseStream2 {
            get {
                return ResourceManager.GetString("mainPauseStream2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        public static string mainProblem {
            get {
                return ResourceManager.GetString("mainProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string mainProgress {
            get {
                return ResourceManager.GetString("mainProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit GRBL-Plotter?.
        /// </summary>
        public static string mainQuit {
            get {
                return ResourceManager.GetString("mainQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string mainSimuSpeed {
            get {
                return ResourceManager.GetString("mainSimuSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start path simulation.
        /// </summary>
        public static string mainSimuStart {
            get {
                return ResourceManager.GetString("mainSimuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop simulation.
        /// </summary>
        public static string mainSimuStop {
            get {
                return ResourceManager.GetString("mainSimuStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming is still active - press Stop and try again.
        /// </summary>
        public static string mainStreamingActive {
            get {
                return ResourceManager.GetString("mainStreamingActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool / Pen change!.
        /// </summary>
        public static string mainToolChange {
            get {
                return ResourceManager.GetString("mainToolChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool change needed:\r.
        /// </summary>
        public static string mainToolChange1 {
            get {
                return ResourceManager.GetString("mainToolChange1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \rpress start to continue..
        /// </summary>
        public static string mainToolChange2 {
            get {
                return ResourceManager.GetString("mainToolChange2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed some unknown G-Code:\r\n.
        /// </summary>
        public static string mainUnknownCode {
            get {
                return ResourceManager.GetString("mainUnknownCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to probing.
        /// </summary>
        public static string probing {
            get {
                return ResourceManager.GetString("probing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing canceled.
        /// </summary>
        public static string probingCancel1 {
            get {
                return ResourceManager.GetString("probingCancel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process last command.
        /// </summary>
        public static string probingCancel2 {
            get {
                return ResourceManager.GetString("probingCancel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to center.
        /// </summary>
        public static string probingCenter {
            get {
                return ResourceManager.GetString("probingCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: no contact.
        /// </summary>
        public static string probingFail1 {
            get {
                return ResourceManager.GetString("probingFail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel probing.
        /// </summary>
        public static string probingFail2 {
            get {
                return ResourceManager.GetString("probingFail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string probingFinish {
            get {
                return ResourceManager.GetString("probingFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing on.
        /// </summary>
        public static string probingProbingOn {
            get {
                return ResourceManager.GetString("probingProbingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set center .
        /// </summary>
        public static string probingSetCenter {
            get {
                return ResourceManager.GetString("probingSetCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time out.
        /// </summary>
        public static string probingTimeOut {
            get {
                return ResourceManager.GetString("probingTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scan.
        /// </summary>
        public static string scan {
            get {
                return ResourceManager.GetString("scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string serialClose {
            get {
                return ResourceManager.GetString("serialClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Connection is needed.\r\nClose main window instead.
        /// </summary>
        public static string serialCloseError {
            get {
                return ResourceManager.GetString("serialCloseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string serialOpen {
            get {
                return ResourceManager.GetString("serialOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check COM-window for further information.
        /// </summary>
        public static string statusStripeCheckCOM {
            get {
                return ResourceManager.GetString("statusStripeCheckCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Check for new GRBL-Plotter release on GitHub&apos; - can be disabled in [Setup - Program control] .
        /// </summary>
        public static string statusStripeCheckUpdate {
            get {
                return ResourceManager.GetString("statusStripeCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt-Click to select Figure; Control-Click to select Group; Shift-Click to select Tile;Or click on XML-Tag.
        /// </summary>
        public static string statusStripeClickKeys {
            get {
                return ResourceManager.GetString("statusStripeClickKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click: mark Figure; Control-Click: mark Group; Shift-Click: mark Tile;Alt-Click: show GCode line.
        /// </summary>
        public static string statusStripeClickKeys2 {
            get {
                return ResourceManager.GetString("statusStripeClickKeys2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control-Down to move selected Block one down; Control-Shift-Down to move to end.
        /// </summary>
        public static string statusStripeDownKeys {
            get {
                return ResourceManager.GetString("statusStripeDownKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit mode on - click into 2D view to finish.
        /// </summary>
        public static string statusStripeEditModeOn {
            get {
                return ResourceManager.GetString("statusStripeEditModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loading.
        /// </summary>
        public static string statusStripeFileLoad {
            get {
                return ResourceManager.GetString("statusStripeFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found - remove from list.
        /// </summary>
        public static string statusStripeFileNotFound {
            get {
                return ResourceManager.GetString("statusStripeFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perhaps serial port is locked and a restart of GRBL-Plotter is needed.
        /// </summary>
        public static string statusStripeGrblResetNeeded {
            get {
                return ResourceManager.GetString("statusStripeGrblResetNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probably a reset of the controller is needed.
        /// </summary>
        public static string statusStripeResetNeeded {
            get {
                return ResourceManager.GetString("statusStripeResetNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection moved by.
        /// </summary>
        public static string statusStripeSelectionMoved {
            get {
                return ResourceManager.GetString("statusStripeSelectionMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming status and G-Code are saved in &apos;_lastProcessed.nc&apos;. Continuation after program restart is possible..
        /// </summary>
        public static string statusStripeStreamingStatusSaved {
            get {
                return ResourceManager.GetString("statusStripeStreamingStatusSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control-Up to move selected Block one up; Control-Shift-Up to move to top.
        /// </summary>
        public static string statusStripeUpKeys {
            get {
                return ResourceManager.GetString("statusStripeUpKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use current settings (last loaded: &apos;{0}&apos;).
        /// </summary>
        public static string useCaseHeader1 {
            get {
                return ResourceManager.GetString("useCaseHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings from &apos;{0}&apos;.
        /// </summary>
        public static string useCaseHeader2 {
            get {
                return ResourceManager.GetString("useCaseHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A use-case is a presetted setup to adjust settings for a specific machine and/or application.\r\nThe settings of a selected and applied use-case also remain after the import of the graphics.\r\nA use-case needs to be stored in \data\usecases to be accessible.\r\nAlso exported machine-settings and sub-sets of it can be used..
        /// </summary>
        public static string useCaseInfo {
            get {
                return ResourceManager.GetString("useCaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string useCaseInfo2 {
            get {
                return ResourceManager.GetString("useCaseInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Current settings ###.
        /// </summary>
        public static string useCaseItem0 {
            get {
                return ResourceManager.GetString("useCaseItem0", resourceCulture);
            }
        }
    }
}
