using System.Globalization;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace GrblPlotter.Wpf.Services;

public sealed class HeightMapPoint
{
    public double X { get; set; }
    public double Y { get; set; }
    public double Z { get; set; }
}

/// <summary>Regular X/Y raster of probed Z values, indexed row-major (iy * GridX + ix).</summary>
public sealed class HeightMap
{
    public int GridX { get; set; } = 5;
    public int GridY { get; set; } = 5;
    public double MinX { get; set; }
    public double MinY { get; set; }
    public double MaxX { get; set; } = 100;
    public double MaxY { get; set; } = 100;
    public List<HeightMapPoint> Points { get; } = new();

    public double CellWidth => GridX > 1 ? (MaxX - MinX) / (GridX - 1) : 0;
    public double CellHeight => GridY > 1 ? (MaxY - MinY) / (GridY - 1) : 0;

    public double? GetZ(int ix, int iy)
    {
        if (ix < 0 || iy < 0 || ix >= GridX || iy >= GridY) return null;
        var idx = iy * GridX + ix;
        return idx >= 0 && idx < Points.Count ? Points[idx].Z : null;
    }
}

/// <summary>Probe pattern generation, CSV persistence, and bilinear Z compensation of loaded g-code.</summary>
public static class HeightMapService
{
    public static List<string> GenerateProbePattern(HeightMap grid, double safeZ, double probeDepth, double probeFeed, double travelFeed, double retract)
    {
        var lines = new List<string>
        {
            "; Height map probe pattern generated by GRBL-Plotter WPF",
            FormattableString.Invariant($"; grid {grid.GridX} x {grid.GridY}  area X[{grid.MinX:0.###}..{grid.MaxX:0.###}] Y[{grid.MinY:0.###}..{grid.MaxY:0.###}]"),
            "G90",
            FormattableString.Invariant($"G0 Z{safeZ:0.###}")
        };

        for (var iy = 0; iy < grid.GridY; iy++)
        {
            var y = grid.MinY + iy * grid.CellHeight;
            var order = Enumerable.Range(0, grid.GridX);
            if (iy % 2 == 1) order = order.Reverse();

            foreach (var ix in order)
            {
                var x = grid.MinX + ix * grid.CellWidth;
                lines.Add(FormattableString.Invariant($"G0 X{x:0.###} Y{y:0.###} F{travelFeed:0.###}"));
                lines.Add(FormattableString.Invariant($"G38.2 G91 Z{probeDepth:0.###} F{probeFeed:0.###}"));
                lines.Add(FormattableString.Invariant($"G91 G0 Z{retract:0.###}"));
                lines.Add("G90");
            }
        }
        lines.Add(FormattableString.Invariant($"G0 Z{safeZ:0.###}"));
        return lines;
    }

    public static void SaveCsv(string path, HeightMap map)
    {
        var sb = new StringBuilder();
        sb.AppendLine(FormattableString.Invariant(
            $"# gridX={map.GridX};gridY={map.GridY};minX={map.MinX};minY={map.MinY};maxX={map.MaxX};maxY={map.MaxY}"));
        sb.AppendLine("x,y,z");
        foreach (var p in map.Points)
            sb.AppendLine(FormattableString.Invariant($"{p.X:0.###},{p.Y:0.###},{p.Z:0.###}"));
        File.WriteAllText(path, sb.ToString());
    }

    public static HeightMap LoadCsv(string path)
    {
        var map = new HeightMap();
        map.Points.Clear();
        double minX = double.MaxValue, minY = double.MaxValue, maxX = double.MinValue, maxY = double.MinValue;
        int gx = 0, gy = 0;

        foreach (var raw in File.ReadAllLines(path))
        {
            var line = raw.Trim();
            if (line.Length == 0) continue;

            if (line.StartsWith('#'))
            {
                foreach (var part in line.TrimStart('#', ' ').Split(';'))
                {
                    var kv = part.Split('=');
                    if (kv.Length != 2) continue;
                    switch (kv[0].Trim())
                    {
                        case "gridX": int.TryParse(kv[1], out gx); break;
                        case "gridY": int.TryParse(kv[1], out gy); break;
                    }
                }
                continue;
            }
            if (line.StartsWith("x,", StringComparison.OrdinalIgnoreCase)) continue;

            var cols = line.Split(',');
            if (cols.Length < 3) continue;
            var x = ParseD(cols[0]);
            var y = ParseD(cols[1]);
            var z = ParseD(cols[2]);
            map.Points.Add(new HeightMapPoint { X = x, Y = y, Z = z });
            minX = Math.Min(minX, x); maxX = Math.Max(maxX, x);
            minY = Math.Min(minY, y); maxY = Math.Max(maxY, y);
        }

        map.MinX = minX == double.MaxValue ? 0 : minX;
        map.MinY = minY == double.MaxValue ? 0 : minY;
        map.MaxX = maxX == double.MinValue ? 0 : maxX;
        map.MaxY = maxY == double.MinValue ? 0 : maxY;

        if (gx > 0 && gy > 0)
        {
            map.GridX = gx;
            map.GridY = gy;
        }
        else
        {
            var guess = Math.Max(1, (int)Math.Round(Math.Sqrt(map.Points.Count)));
            map.GridX = guess;
            map.GridY = (int)Math.Ceiling(map.Points.Count / (double)guess);
        }
        return map;
    }

    public static double Interpolate(HeightMap map, double x, double y)
    {
        if (map.Points.Count == 0) return 0;
        if (map.GridX < 2 || map.GridY < 2) return map.Points[0].Z;

        var fx = (x - map.MinX) / (map.CellWidth <= 0 ? 1 : map.CellWidth);
        var fy = (y - map.MinY) / (map.CellHeight <= 0 ? 1 : map.CellHeight);
        fx = Math.Clamp(fx, 0, map.GridX - 1);
        fy = Math.Clamp(fy, 0, map.GridY - 1);

        var ix0 = (int)Math.Floor(fx);
        var iy0 = (int)Math.Floor(fy);
        var ix1 = Math.Min(ix0 + 1, map.GridX - 1);
        var iy1 = Math.Min(iy0 + 1, map.GridY - 1);
        var tx = fx - ix0;
        var ty = fy - iy0;

        var z00 = map.GetZ(ix0, iy0) ?? 0;
        var z10 = map.GetZ(ix1, iy0) ?? z00;
        var z01 = map.GetZ(ix0, iy1) ?? z00;
        var z11 = map.GetZ(ix1, iy1) ?? z10;

        var top = z00 + (z10 - z00) * tx;
        var bottom = z01 + (z11 - z01) * tx;
        return top + (bottom - top) * ty;
    }

    private static readonly Regex WordRx = new(@"([GMTXYZABCIJKFSP])\s*([-+]?(?:\d+\.?\d*|\.\d+))",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex ZWordRx = new(@"Z\s*[-+]?(?:\d+\.?\d*|\.\d+)", RegexOptions.IgnoreCase | RegexOptions.Compiled);

    /// <summary>Rewrites Z values of every motion line by adding the bilinear-interpolated height map offset at that X/Y.</summary>
    public static List<string> ApplyToGCode(IReadOnlyList<string> lines, HeightMap map)
    {
        var result = new List<string>(lines.Count);
        double x = 0, y = 0, z = 0;
        var absolute = true;

        foreach (var raw in lines)
        {
            var line = raw.Split(';')[0].Trim();
            if (line.Length == 0 || line.StartsWith('(') || line.StartsWith('#'))
            {
                result.Add(raw);
                continue;
            }

            double? nx = null, ny = null, nz = null;
            var hasMotion = false;

            foreach (Match m in WordRx.Matches(line))
            {
                var letter = char.ToUpperInvariant(m.Groups[1].Value[0]);
                var val = double.Parse(m.Groups[2].Value, CultureInfo.InvariantCulture);
                switch (letter)
                {
                    case 'G':
                        var g = (int)val;
                        if (g is 0 or 1 or 2 or 3) hasMotion = true;
                        if (g == 90) absolute = true;
                        if (g == 91) absolute = false;
                        break;
                    case 'X': nx = val; break;
                    case 'Y': ny = val; break;
                    case 'Z': nz = val; break;
                }
            }

            if (!hasMotion && nx is null && ny is null && nz is null)
            {
                result.Add(raw);
                continue;
            }

            var x1 = nx.HasValue ? (absolute ? nx.Value : x + nx.Value) : x;
            var y1 = ny.HasValue ? (absolute ? ny.Value : y + ny.Value) : y;
            var baseZ = nz.HasValue ? (absolute ? nz.Value : z + nz.Value) : z;
            x = x1; y = y1; z = baseZ;

            var comp = Interpolate(map, x1, y1);
            var outZ = baseZ + comp;

            var newLine = nz.HasValue
                ? ZWordRx.Replace(line, FormattableString.Invariant($"Z{outZ:0.###}"))
                : line + FormattableString.Invariant($" Z{outZ:0.###}");
            result.Add(newLine);
        }
        return result;
    }

    private static double ParseD(string s) =>
        double.TryParse(s.Trim(), NumberStyles.Float, CultureInfo.InvariantCulture, out var d) ? d : 0;
}
